version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - DATABASE_URL=sqlite:///./data/feedback.db
      - QDRANT_MEMORY=false
      - QDRANT_PATH=/app/data/qdrant_storage
    volumes:
      - ./data:/app/data
      - ./backend:/app/backend
    networks:
      - mathai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000/api
    depends_on:
      - backend
    networks:
      - mathai-network
    restart: unless-stopped

networks:
  mathai-network:
    driver: bridge

volumes:
  mathai-data: